apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-catalog-service
  labels: 
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: bookstore-catalog-service
        image: sunildevops1/bookstore-catalog-service:12
        imagePullPolicy: Always
        ports:
          - containerPort: 6001
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: "-Dspring.profiles.active=local"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 6001
    targetPort: 6001
