apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-eureka-discovery-service
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: bookstore-eureka-discovery-service
        image: sunildevops1/bookstore-eureka-discovery-service:15
        ports:
          - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
